export interface AssetData {
  id: number;
  AssetName: string;
  URN: string;
  URIAssetID: string;
  FLX_AssetID: string | null;
  assetTransferedDate: string | null;
  metadataCreated: string;
  metadataModified: string;
  URIDevice: string;
  URILocation: string;
  URICategory: string;
  URIFormat: string;
  MarkIn: string;
  MarkOut: string;
  Duration: string;
  durration_in_flx: string | null;
  flx_folder_tag: string | null;
  Height: number | null;
  Width: number | null;
  VideoCompressionName: string;
  AudioFormatName: string;
  VideoFormatName: string;
  NumVideo: number;
  NumAudio: number;
  NumTC: number;
  AspectRatio: number;
  metadataID: string;
  Rating: string | null;
  Tags: string | null;
  Restriction: string;
  Date_Of_Transmission: string | null;
  extendedComments: string | null;
  Archives_ID: string | null;
  Agency_Restrictions: number;
  Entity_Type: string | null;
  Lock_Asset: number;
  Content_Location: string | null;
  Commissioning_Unit: string;
  CoDA: number;
  Approval_Status: string | null;
  Personalities: string | null;
  Longitude: string;
  Branch: string | null;
  Rights_Holder: string | null;
  CoDA_ID: string;
  Reporter: string | null;
  Description: string;
  Advisory: string | null;
  Contains_Restricted_Footage: number;
  Program_Number: string | null;
  Presenter: string | null;
  ENPS_ID: string;
  Content_Warning: string;
  Subject_Person: string | null;
  Date_Of_Record: string | null;
  CoDA_OnAir: number;
  Subject_Topic: string | null;
  Camera_Operator: string | null;
  Transcript: string | null;
  Info_Source: string;
  CoDA_Title: string;
  LockAsset: string;
  LanguageAndSoound: string;
  Lattitude: string;
  CataloguerSInitials: string | null;
  status: string;
  error_message: string | null;
  isScaned: number;
  scanStatus: string | null;
  scan_remark: string | null;
}